### ISSUE TITLE
What's the monthly traffic on your blog at the moment?

### ISSUE THREAD

**Issue by amitmerchant1990** [flaviocopes/ama#12]

**Comment by flaviocopes** [comment]
I prefer not to answer, as it varies a lot by month and even if I answer, the answer will be outdated next month :) just adding that online sites that try to "guess" the number of visits (I'm thinking of one or two in particular) are usually way overestimating the number of visits.

**Comment by amitmerchant1990** [comment]
I think I've put the question in clear perspective now. What do you think?

**Comment by flaviocopes** [comment]
Not everyone likes or is comfortable to openly talk about numbers, revenue etc. Some people do. I don't :)

**Comment by amitmerchant1990** [comment]
No problem then. :)
